### ISSUE TITLE
Change the display of pollination information so it is more visible

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#114]
- Remove from Show all Characteristics > Facts and Uses
- Insert under Facts About between the paragraph with general information and the final paragraph with the conservation statement (although they are flexible about the placement and happy to listen if we have a suggestion)

@davisagli you estimated this at 1-2 hours. Assigning this to you to work on the week of 12/12/2016.

**Comment by davisagli** [comment]
This was actually quite trivial, and is now done. I put it under a "Pollination" heading below the paragraph with the conservation statement rather than as part of the Facts About section, because the example I looked at needed the header for context. But it's easy to move if they want to adjust further.

**Comment by skleinfeldt** [comment]
Thank you @davisagli and thanks from Jay, who says: This looks exactly as we hoped it would and I think it's a real bonus having the pollinator information up front.

He has a question about an optional refinement which I'm going to put on another ticket and close this one.
