### ISSUE TITLE
Change to the About page

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#120]
NEWFS has changed its name. 

Change the text under "Our Partner Project" to  "...educational website of the Native Plant Trust, formerly the New England Wild Flower Society..."

Native Plant Trust should link to https://www.nativeplanttrust.org/

Go Botany should link to https://gobotany.nativeplanttrust.org/

Remove the sentence "Interactive dichotomous identification keys based on the Flora Novae Angliae (Haines 2011) are also available."

They'd like to replace the logo, but it isn't clear to me what to replace it with, maybe https://www.nativeplanttrust.org/static/images/npt-logo-stacked.svg? If that isn't workable,  remove the logo for now.

**Comment by skleinfeldt** [comment]
Jay confirms that is the logo they want to use.

**Comment by alecpm** [comment]
That's editable as HTML in the Django Admin:

https://goorchids-heroku-18.herokuapp.com/admin/flatpages/flatpage/1/

**Comment by alecpm** [comment]
Or on production:

http://goorchids.northamericanorchidcenter.org/admin/flatpages/flatpage/1/

**Comment by skleinfeldt** [comment]
I thought that might be the case. But I'm not sure Jay's comfort level doing it. I'll ask.

**Comment by skleinfeldt** [comment]
Jay says he tried editing the flat page on the test site:
"no problems...however I can't add the new Plant Trust logo.
I did find one possible issue on this flat page.
I was not able to view the page (button on the upper right). I got a page not found. However when I went to a TAXA page, I was able to view the changes on the ABOUT page."

@alecpm can you either add the logo or tell me how so I can tell Jay. Also is the view page error an issue that needs to be addressed?

**Comment by alecpm** [comment]
Unless the logo looks good on that background and size, I think it's probably best to remove the logo, especially since we don't know what their preferred logo might be. It seems the most comparable one to the existing one is this:

https://gobotany.nativeplanttrust.org/static/images/layout/npt-gb-logo-home.svg

That won't work on that page though unless we add a background color like #428b3d as they use on their website header. You can see it without the logo here:

https://goorchids-heroku-18.herokuapp.com/about/

The inability to preview flat pages appears to be a long standing bug, and is related to the fact that you can register flat pages for different domains and the one that is used for GoOrchids is a loop back domain which won't work for previews (unless you are developing). It's probably not worth digging into at this moment, and it's certainly not anything new.

**Comment by skleinfeldt** [comment]
Jay is good with getting rid of the image and he's able to fix the text himself, so closing.
