### ISSUE TITLE
Cannot log into admin site

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#150]
From Jay: 
I’ve been trying to get into the go orchids admin site and keep getting an error that takes me to this page:
[Logging | Heroku Dev Center](https://devcenter.heroku.com/articles/logging#view-logs)

This is about the production admin site.

**Comment by chiruzzimarco** [comment]
@skleinfeldt I don't have any issue in logging into the production admin site. On the other hand the staging environment was down due to some latest fixes that were applied to the production environment but were missing here. I had no issues in logging in the admin site on the staging environment either once restored.

**Comment by skleinfeldt** [comment]
Jay was able to log in, so closing.
